const Map<int, String> planes = {
  1: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/jkg9ayc8q1_en.jpg',
  2: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/2wt5i8bgv9_en.jpg',
  3: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/j80y286cwa_en.jpg',
  4: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/c1482p4meu_en.jpg',
  5: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/2wt5i8bgv9_en.jpg',
  6: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/lsrhf23ijc_en.jpg',
  7: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/aye2m5mvjh_en.jpg',
  8: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/37pm7bjwg4_en.jpg',
  9: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/iq2f02fpgn_en.jpg',
  10: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/kpyyk46oku_en.jpg',
  11: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/54lws2gj6o_en.jpg',
  12: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/896l8oejua_en.jpg',
  13: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/o4qb9nc5u5_en.jpg',
  14: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/jaau04l4cz_en.jpg',
  15: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/4jynnjp4xz_en.jpg',
  16: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/8ylydlg0yz_en.jpg',
  17: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/1hptx2gw1c_en.jpg',
  18: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/d82cvyphai_en.jpg',
  19: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/1klu7o8una_en.jpg',
  20: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/3ns1mv62gs_en.jpg',
  21: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/k1ezql7m4n_en.jpg',
  22: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/98czx7j61z_en.jpg',
  23: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/gcszz5kdkr_en.jpg',
  24: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/thcuk2hbiw_en.jpg',
  25: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/v1twzuldqa_en.jpg',
  26: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/1ef1gmo0od_en.jpg',
  27: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/um4917wswq_en.jpg',
  28: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/74ldmujlak_en.jpg',
  29: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/n30djv44kv_en.jpg',
  30: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/17sst7nb6f_en.jpg',
  31: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/rc3eui4rmv_en.jpg',
  32: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/pkkkbzxy4g_en.jpg',
  33: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/wh9hqj2ilg_en.jpg',
  34: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/6v9xkf46zk_en.jpg',
  35: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/7dl00hhj9w_en.jpg',
  36: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/x82u3qdcaj_en.jpg',
  37: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/uqbfnpsyvy_en.jpg',
  38: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/kust0ebnd5_en.jpg',
  39: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/ve4qhhx1e1_en.jpg',
  40: 'https://media.magic.wizards.com/image_legacy_migration/images/magic/tcg/products/pc2/btblskt8iq_en.jpg',
};

const Map<int, String> planesText = {
  1: 'Quando entrar nesse Phenomeno, Enquanto extiver no proximo plano, cada rolagem de dados em branco, vale como uma rolagem de bolinha',
  2: 'Quando entrar nesse Phenomeno, Cada jogador compra 4 cartas.',
  3: 'Quando entrar neste Phenomeno, cada jogador embaralha todas as permanetes que controla no proprio grimorio.\nDepois revela aquela quantidade de cartas do topo do grimorio. Cada jogador coloca todas as criaturas, artefatos, terrenos e planeswalkers revelados dessa maneira no campo de batalha. Depois faz a mesma coisa para cada encantamento. Depois as cartas que nao foram colocadas no campo de batalha sao colocadas no fundo do grimorio.',
  4: 'Criaturas com voar ganham +2/+0.\nCriaturas sem voar ganham -2/-0',
  5: 'Quando entrar nesse Phenomeno, Cada jogador compra 4 cartas.',
  6: 'Quando entrar nesse Phenomeno, destrua todas as criaturas.',
  7: 'Quando entrar nesse Phenomeno, comecando de voce, cada jogador pode colocar uma permanente de sua mao no campo de batalha',
  8: 'Quando entrar nesse Phenomeno, passe os dois proximos planos (execute como se mudasse desses planos)',
  9: 'Quando entrar nesse Phenomeno, inverta a ordem dos turnos',
  10: 'Jogadores podem conjurar encantamentos como se tivessem flash.',
  11: 'Quando voce chega nesse plano ou no comeco do upkeep, coloque um contador de SCROLL em Aretopolis.\nDepois voce ganha pontos de vida igual a quantidade de contadores.\n\nQuando Aretopolis tiver 10 ou mais contadores, mude o plano.',
  12: 'Somente uma criatura pode atacar a cada combate.\n\nSomente uma criatura pode bloquear a cada combate.',
  13: 'Quando uma criatura entrar no campo de batalha ela ganha impeto e golpe duplo ate o final do turno.',
  14: 'Se uma criatura que voce controla fosse desvirar na etapa de desvirar, ela nao desvira e voce coloca 2 contadores +1/+1 nela',
  15: 'Quando voce chegar neste plano ou no comeco do seu upkeep, selecione um jogar aleatoriamente,\nAquele jogador descarta uma carta.\nSe aquele jogador descartar um terreno, ele perde 3 pontos de vida.',
  16: 'Todas criaturas tem vigilancia',
  17: 'No final do combate, voce pode permutar o controle da criatura que voce controla que causou dano a um jogador nesse turno, com uma criatura que aquele jogador controla.',
  18: 'Quando uma criatura morrer, seu controlador distribui uma quantidade de contadores +1/+1 igual ao poder daquela criatura, em qualquer numero de criaturas que ele controla',
  19: 'Quando voce chegar nesse plano ou no comeco de seu upkeep, revele cartas do topo do grimorio ate revelar uma carta de criatura.\nColoque aquele card no campo de batalha e o resto no fundo do grimorio.',
  20: 'Criaturas com poder igual ou maior que 7 nao podem atacar nem bloquear',
  21: 'Quando um jogador conjurar uma magica de criatura preta, vermelha ou verde, ela ganha Devorar 5. \n\n(Quando essa criatura entra no campo de batalha, seu controlador pode sacrificar qualquer numero de outras criaturas. Aquela criatura entra no campo de batalha com 5 vezes o numero de criaturas sacrificadas, de contadores +1/+1.)',
  22: 'Previna todo dano de combate que seria causado por criaturas que nao sejam Lobisomen',
  23: 'Quando uma criatura que voce controla ataca um oponente, para cada outro oponente, crie uma ficha que seja copia daquela atacante, atacando cada outro oponente.\n\nExile essas fichas no final do end step.',
  24: 'Quando voce chegar nesse plano ou no comeco do pre-combate, coloque um contador de carga em Kilnspire District e depois adiciona mana vermelha igual ao numero de contadores de carga no plano.',
  25: 'No comeco do seu upkeep, sacrifique uma criatura. Se voce nao puder, mude para o proximo plano.',
  26: 'No comeco do end step, coloque um contador de PRESSURE em Mount Keralia.\nQuando voce deixar esse plano, ele causa dano igual ao numero de contadores em cada criatura e cada planeswalker.',
  27: 'No comeco do end step, coloque as sete cartas do topo do grimorio no cemiterio. \nDepois retorne uma carta aleatoria do cemiterio para a sua mao.',
  28: 'Quando voce deixar esse plano, destrua cada permanente que nao tenha um contador de FATE.\nDepois remova todos os contadores de FATE de todas as permanentes.',
  29: 'Todas as criaturas sao pretas e tem toque mortiferio.',
  30: 'Quando uma criatura que voce controla causar dano de combate a um jogador, voce pode procurar um card de terreno basico no seu grimorio e coloca-lo no campo de batalha virado.\nDepois embaralhe sem grimorio.',
  31: 'Quando voce deixar esse plano cada jogador retorna todas as criaturas do seu cemiterio para o campo de batalha.',
  32: 'Se voce conjurou uma magica esse turno, voce nao pode atacar com criaturas.\n\nSe voce atacou com criaturas neste turno, voce nao pode conjurar magicas.',
  33: 'Quando voce chegar nesse plano, ou no comeco do upkeep, scry 4.',
  34: 'Se um efeito criaria um ou mais fichas, crie 2 vezes essa quantidade de fichas.\n\nSe um efeito faria com que um ou mais contadores fossem colocados em uma permanente, coloque o dobro de contadores.',
  35: 'Quando uma criatura causar dano de combate a um ou mais jogadores pela primeira vez no turno, coloque um marcador +1/+1 nela.',
  36: 'Quando uma criatura deixar o campo de batalha, seu controlador compra uma carta.',
  37: 'A qualquer momento que voce possa conjurar um feitico, voce pode exilar uma carta nao terreno de sua mao com X contadores de TIME nela onde X é seu custo de mana convertido.\n\nSe o card exilado nao tinha suspend, ele ganha suspend.',
  38: 'Magicas instantaneas e feiticos tem rebound. \n\n(O controlador daquela magica exila ela quando ela resolver. No inicio do proximo upkeep daquele jogador ele pode conjurar esta carta do exilio sem pagar seu custo de mana)',
  39: 'Todos os terrenos tem: \"Vire: adicione uma mana de qualquer cor a sua reserva de mana\"',
  40: 'Jogadores jogam com a carta do topo reveladas.\nVoce pode conjurar a carta do topo do grimorio de qualquer jogador.',
};

const Map<int, String> planesChaosText = {
  1: '',
  2: ' ',
  3: '',
  4: 'A Criatura alvo ganha voar ate o final do turno',
  5: '',
  6: ' ',
  7: ' ',
  8: ' ',
  9: ' ',
  10: 'Destroi a criatura alvo que nao está encantada',
  11: 'Coloque um contador de scroll no plano, depois compre a quantidade de cartas igual ao numero de contadores de scroll no plano',
  12: 'Astral Arena causa 2 pontos de dano a cada criatura',
  13: 'Exile a criatura nao token que voce controla e depois volte ela para o campo de batalha sob o seu controle.',
  14: 'Desvire cada criatura que voce controla',
  15: 'Voce pode destruir a permanente alvo que nao seja terreno',
  16: 'Criaturas que voce controla sao indestrutiveis ate o final desse turno',
  17: 'Ganhe controle da criatura alvo que pertence a voce',
  18: 'Cada jogador exila todas as criaturas que controla e coloca X tokens 1/1 do tipo Saproling no campo de batalha, sendo X o total de poder somado das criaturas exiladas.\nE depois muda de plano.',
  19: 'Retorne a criatura alvo do seu cemiterio para o campo de batalha',
  20: 'Coloque uma ficha incolor de Eldrazi 7/7 com aniquilator 1 no campo de batalha',
  21: 'Coloque 2 fichas de Goblin 1/1 no campo de batalha',
  22: 'Cada criatura que voce controla ganha +2/+2, atropelar, e se torna um Lobisomen em adicao aos seus tipos ate o final do turno',
  23: 'Voce pode sacrificar qualquer numero de criaturas.\nSe fizer isto, Kharasha Foothills causa aquela quantidade de dano a criatura alvo',
  24: 'Voce pode pagar X.\n Se o fizer, Kilnspire District causa X de dano a criatura ou jogador alvo',
  25: 'Qualquer numero de jogadores alvo cria uma ficha de zumbi 2/2 e coloca no campo de batalha',
  26: 'Prevne todo dano que o plano Mount Keralia causaria nesse game as permanentes que voce controla',
  27: 'Retorne o card alvo do seu cemiterio para sua mao',
  28: 'Voce pode colocar um contador de FATE na permanente alvo',
  29: 'Criaturas que voce controla ganham +1/+0 e iniciativa ate o final do turno',
  30: 'A criatura alvo nao pode ser bloqueada neste turno.',
  31: 'Para cada oponente, exile ate um card de criatura do cemiterio daquele jogador',
  32: 'Voce ganha a quantidade de vida igual a quantidade de cartas na sua mao',
  33: 'Revele a carta do topo do seu grimorio. Voce pode jogar aquela carta sem pagar seu custo de mana.',
  34: 'Ate o final do turno, quando voce virar um terreno para gerar mana, adiciona uma mana adicional do tipo que aquele terreno pode produzir',
  35: 'Ate o final do turno, Cada criatura que voce controla ganha: \nVire: Esta criatura causa 1 ponto de dano ao jogador alvo.',
  36: 'Retorne a criatura alvo que voce controla para a mao do seu dono.',
  37: 'Remove 2 contadore de TIME de cada carta que voce controla com suspend',
  38: 'Voce pode procurar em seu grimorio por uma carta de instant ou feitico e coloca-la em sua mao, depois embaralhe seu grimorio',
  39: 'Revele as tres cartas do topo do seu grimorio.\nColoque todos os terrenos revelados na sua mao e resto no fundo do grimorio em qualquer ordem',
  40: 'Cada jogador colocaa carta do topo do grimorio no cemiterio',
};
